import Head from "next/head";
import MaxWidthWrapper from "~/components/layout/max-width-wrapper";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "~/components/ui/tabs";
import Certificates from "../../components/profile/profile-certificate";
import Profile from "~/components/profile/profile";
import { EditProfile } from "~/components/profile/profile-edit";
export default function MainProfile() {
  return (
    <>
      <Head>
        <title>CSI NMAMIT</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="bg-white text-black transition-colors duration-500 dark:bg-gray-900/10 dark:text-white">
          <div className="mt-7 flex flex-col items-center justify-center text-center">
            <MaxWidthWrapper>
              <Tabs defaultValue="profile">
                <TabsList>
                  <TabsTrigger value="profile">Profile</TabsTrigger>
                  <TabsTrigger value="edit">Edit</TabsTrigger>
                  <TabsTrigger value="certificates">Certificates</TabsTrigger>
                </TabsList>
                <TabsContent value="profile">
                  <Profile />
                </TabsContent>
                <TabsContent value="edit">
                  <EditProfile/>
                </TabsContent>
                <TabsContent value="certificates">
                  <Certificates />
                </TabsContent>
              </Tabs>
            </MaxWidthWrapper>
          </div>
        </section>
      </main>
    </>
  );
}
