import Head from "next/head";
import AboutUs from "~/components/aboutus";
import Hero from "~/components/hero";
import HomePage from "~/components/home-page";

export default function Home() {
  console.log("Firebase API Key:", process.env.NEXT_PUBLIC_FIREBASE_API_KEY);

  return (
    <>
      <Head>
        <title>CSI NMAMIT</title>
        <meta name="description" content="Generated by create-t3-app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main>
        <Hero />
        <hr className="border-black-500/50" />
        <AboutUs />
        <hr className="border-black-500/50" />
        <HomePage />
      </main>
    </>
  );
}
